### ISSUE TITLE
Metrics Dashboard

### ISSUE THREAD

**Issue by rgaudin** [offspot/metrics#1]
This is an EPIC project that shall be split into smaller tickets as design and implementation progresses

Original request is at https://github.com/offspot/package-requests/issues/17

## Objective

A new on-device service that displays a dashboard providing content-oriented usage metrics.
This dashboard is public and targets primarily the _Hotspot Admin_ (the person _managing_ the Hotspot).
It aims at providing useful information on the Hotspot usage.

What _useful information_ are is not defined at the moment. Initial goal is to provide _obviously useful_ data so the feature can be deployed and needs can be gathered from actual usage.

## Details

- Will work mostly off reverse-proxy logs (other non-visit-related data could be added in the future like Hotspot operating hours)
- Reverse-proxy's logs config is still open
  - Caddy offers very verbose JSON logs but we'd prefer working off a standard
  - [NCSA Log format](https://en.wikipedia.org/wiki/Common_Log_Format) is a possibility
  - [nginx's combined](https://nginx.org/en/docs/http/ngx_http_log_module.html#log_format) (its default) is also 
  - Whether we'll have one or multiple source of logs is unclear
  - Looks like we could stream the logs right from the proxy to another tool… but maybe filesystem is safer
- As logs are only produced for this purpose, it is this tool's responsibility to handle its lifecycle. Configuring the reverse-proxy to rotate them is a possibility.
- Log parsing is not something we want to do ourselves ; we should find a reliable tool for that
- If/How the tool keeps an intermediate representation of data is to be defined.

---

- Dashboard needs to be limited, simple and non-technical
- It will be interactive but  limited to the precomputed datasets
- We want to have a list of modules (Outputs) that either work off the global dataset (multiple content packages) or a single package.
- All modules accepts flexible data points that can represent a Day, a Week, a Month, a Year or maybe other periods.
- Aggregation periods are to be defined.
- Whether we keep raw data (if we don't process them live) and for how long is to be defined.
- It is understood that past reports (reports generated for past periods) are immutable. When we compute data for day `x`, the _month_ aggregate for `x - 60` is not computed again.
- Modules could accept _filters_ so they are computed on a subset of their initial dataset. When a user request a filtered-report, it will be available from next-computation and be generated each time unless it is deleted.

---

- Data must be pre-computed so that the UI only serves already-generated data. This is to reduce on-demand resource usage and to facilitate export of such data.
- Hotspot has a YAML file that contains a list of all the content packages with their internal links. That would be used to match requests with Content Packages
 - When processing will be ran is also to be defined. Hotspot are not always-on servers so scheduling must be thought after.

### Multi-content

- Content popularity (Sorted nb of hits to home url of each content)

### Single content

- Top _50_ most accessed pages (Sorted nb of hits inside content, resources (css/js/fonts/etc) excluded)

## Future

In the future, a Cloud version aggregating data from many Hotspot would be developed.

**Comment by benoit74** [comment]
Sorry for the french below.

Planification supposant un travail de dev uniquement par moi, focus à 100% sur cette tâche, à 30% sur juin puis 80% à partir du 1er juillet.

- Architecture de la solution : 1J (W21)
- Mise en place du backend (structure minimale de code, CI/CD) : 1J (W21)
- Codage de la logique métier (y compris stockage en DB) : 4J (W22-23-24)
- Codage des inputs / indicateurs / KPIs de la v1 : 0.5J (W25)
- Codage d'un simulateur : 1J (W25)
- Tests avec simulateur + fix : 0.5J (W25)
- Ingestion des logs de Caddy : 2J (W26 + W27)
- Mise en place du front-end (structure minimale de code, CI/CD) : 1J (W27)
- Codage du front-end + API back (y compris maquette graphique) : 4J (W27+ W28)
- Revue finale documentation (design) : 0.5J (W28)
- Publication de l'image Docker et intégration au offspot : 0.5J (W28)

Reste 1J de dispo W28 dans ce planning, donc avec de la contingence (parce qu'il va bien y avoir des surprises) je dirais fin du projet en milieu de W29 pour être réaliste.

A lancer semaine prochaine (W25) avant les vacances et pour profiter de ma présence à Lausanne le vendredi :
- discussion sur Logstash
- discussion sur le simulateur 
- discussion sur la maquette graphique du front

Pas inclus :
- Intégration directe à Kiwix-serve ou au hot spot actuel (au moins test + documentation) : 2J

WDYT about this plan ? Do you wanna me to create issues for each point above so that we have a more detailed follow up (not sure if it ads much value compared to weekly reporting in this issue) ?

**Comment by rgaudin** [comment]
Great 👍
