### ISSUE TITLE
Better responsiveness of the top toolbar on medium screens

### ISSUE THREAD

**Issue by rgaudin** [offspot/metrics#77]
I don't know if it's tracked in a different issue since UI hasn't been completely implemented by there are issue with small screens: the back/previous buttons are missing in some sizes.
I don't know what are the defined size screen requirements but even on an iPad view, the button is truncated

![Screen Shot 2023-12-20 at 12 17 01](https://github.com/offspot/metrics/assets/57929/df9f3adb-c627-4918-bbae-7e9f19e1a3b0)

**Comment by benoit74** [comment]
This is a known issue because this toolbar is not at all designed as intended for now, it is just a minimal UI.
Real work will be done in #51.
Thank you for reporting this anyway.
I will keep this open until #51 is implemented, should we decide to not do this issue straightaway, we should not forgot that there is still a minimal work to do in terms of responsiveness of the toolbar.
